Name: Tomcat Application Server for Chef Server (RightLink 10)
Description: "Tomcat Application Server for Chef Server (RightLink 10) ServerTemplate.
  \  RightLink10 is a new agent to connect servers to the RightScale platform that
  is very lightweight and simple to install.\r\n_It is not a plug-in upgrade from
  the older RightLink v6 series._\r\nSee [http://docs.rightscale.com/rl/about.html](http://docs.rightscale.com/rl/about.html)
  for details.\r\n\r\nIn addition to installing Tomcat, this ServerTemplate runs a
  script to update the packaging system and enable automatic security updates, and
  a collectd install script to enable RightScale monitoring. \r\n\r\nThe ServerTemplate
  can run on most any Linux distro that supports cloud-init. It is recommended to
  use the standard distro images in various clouds.\r\n\r\n__ Requirements__\r\n\r\n
  * Chef Server or Hosted Chef\r\n * [rsc_tomcat](https://github.com/rightscale-services-cookbooks/rsc_tomcat)
  ([1.2.0](https://github.com/rightscale-services-cookbooks/rsc_tomcat/releases/tag/v1.2.0))\r\n
  * [rsc_remote_receipt](https://github.com/rightscale-services-cookbooks/rsc_remote_receipe)
  ([10.0.0](https://github.com/rightscale-services-cookbooks/rsc_remote_recipe/releases/tag/v10.0.0))\r\n\r\n__Key
  Features:__\r\n\r\n* Sets up and launches a Tomcat application server in any of
  the supported cloud infrastructures.\r\n* Connections to a MySQL database.\r\n*
  Attach/Detach application servers to a HAProxy load balancer.\r\n* Basic set of
  recipes for a RightLink-based server with logging, monitoring, alerts, tagging,
  etc.\r\n* MultiCloud Images that reference the latest supported images with a frozen
  and tested software repository date.\r\n* Basic set of alerts for most server type
  monitoring.\r\n* Examples of system-required input variables.\r\n\r\n\r\n* * *\r\n\r\n__Tested
  Linux distros:__\r\n\r\n* Ubuntu 14.04 x86_64\r\n\r\n\r\n__Tested compute clouds:__\r\n\r\n*
  AWS"
Inputs:
  APPLICATION_NAME: blank
  APPLICATION_ROOT_PATH: blank
  BIND_NETWORK_INTERFACE: blank
  CHEF_SERVER_SSL_CERT: blank
  CHEF_SERVER_URL: blank
  CHEF_VALIDATION_KEY: blank
  CHEF_VALIDATION_NAME: blank
  COLLECTD_SERVER: env:RS_TSS
  LISTEN_PORT: blank
  PACKAGES: blank
  REFRESH_TOKEN: blank
  RS_INSTANCE_UUID: env:RS_INSTANCE_UUID
  SCM_DEPLOY_KEY: blank
  TOMCAT_APPLICATION_NAME: blank
  TOMCAT_DATABASE_HOST: blank
  TOMCAT_DATABASE_PASSWORD: blank
  TOMCAT_DATABASE_SCHEMA: blank
  TOMCAT_DATABASE_USER: blank
  TOMCAT_VHOST_PATH: blank
  TOMCAT_WAR_PATH: blank
  VERSION: text:12.16
  VHOST_PATH: blank
RightScripts:
  Boot:
  - Name: RL10 Linux Wait For EIP
    Revision: 5
    Publisher: RightScale
  - Name: RL10 Linux Setup Hostname
    Revision: 7
    Publisher: RightScale
  - Name: RL10 Linux Enable Managed Login
    Revision: 10
    Publisher: RightScale
  - Name: RL10 Linux Setup Alerts
    Revision: 1
    Publisher: RightScale
  - Name: RL10 Linux Setup Automatic Upgrade
    Revision: 2
    Publisher: RightScale
  - Name: Chef Client Install
    Revision: 4
    Publisher: RS Professional Services
  - Name: RS-Base Install - chef
    Revision: 1
    Publisher: RS Professional Services
  - Tomcat_Appserver_Install-chef.sh
  - Tomcat_Appserver_Application_Backend-chef.sh
  Decommission:
  - Name: RL10 Linux Shutdown Reason
    Revision: 4
    Publisher: RightScale
  - Tomcat_Appserver_Application_Backend_Detach-chef.sh
  - Name: Chef Client Delete Node
    Revision: 5
    Publisher: RS Professional Services
  Operational:
  - Tomcat_Appserver_Application_Backend-chef.sh
  - Tomcat_Appserver_Application_Backend_Detach-chef.sh
  - Name: RL10 Linux Setup Automatic Upgrade
    Revision: 2
    Publisher: RightScale
  - Name: RL10 Linux Upgrade
    Revision: 6
    Publisher: RightScale
MultiCloudImages:
  - Name: Ubuntu_14.04_x64
    Revision: 55
    Publisher: RightScale
  - Name: Ubuntu_14.04_x64_KVM
    Revision: 29
    Publisher: RightScale
  - Name: Ubuntu_12.04_x64
    Revision: 54
    Publisher: RightScale
  - Name: Ubuntu_12.04_x64_KVM
    Revision: 29
    Publisher: RightScale
  - Name: CentOS_6.7_x64
    Revision: 21
    Publisher: RightScale
  - Name: CentOS_6.x_x64_KVM
    Revision: 28
    Publisher: RightScale
  - Name: CentOS_7.1_x64
    Revision: 29
    Publisher: RightScale
  - Name: CentOS_7.2_x64_KVM
    Revision: 27
    Publisher: RightScale
  - Name: RHEL_6.x_x64_KVM
    Revision: 6
    Publisher: RightScale
  - Name: RHEL_7.x_x64_KVM
    Revision: 7
    Publisher: RightScale
  - Name: RHEL_6.8_x64
    Revision: 9
    Publisher: RightScale
  - Name: RHEL_7.2_x64
    Revision: 7
    Publisher: RightScale
Alerts:
- Name: instance terminated
  Description: Raises alert if instance terminates abnormally, i.e., not through the
    RightScale interface or by an elasticity daemon (only for server arrays).
  Clause: If RS/server.state == terminated for 1 minutes Then escalate critical
- Name: instance stranded
  Description: Raises alert if instance enters the stranded state.
  Clause: If RS/server-failure.state == stranded for 1 minutes Then escalate warning
- Name: instance not responding
  Description: Raises alert if instance fails to send monitoring information within
    a given duration, based on the conditions set for this alert.
  Clause: If cpu-0/cpu-idle.value == NaN for 30 minutes Then escalate warning
- Name: cpu busy
  Description: Raises alert if average idle time is too low, based on the conditions
    set for this alert.
  Clause: If cpu-0/cpu-idle.value < 15 for 60 minutes Then escalate warning
- Name: cpu overloaded
  Description: Raises alert if average idle time is too low, based on the conditions
    set for this alert.
  Clause: If cpu-0/cpu-idle.value < 3 for 30 minutes Then escalate critical
- Name: cpu I/O wait
  Description: Raises alert if average disk I/O is too high, based on the conditions
    set for this alert.
  Clause: If cpu-0/cpu-wait.value > 40 for 30 minutes Then escalate warning
- Name: high network rx activity
  Clause: If interface-eth0/if_octets.rx > 50000000 for 30 minutes Then escalate critical
- Name: 'high network tx activity '
  Clause: If interface-eth0/if_octets.tx > 50000000 for 30 minutes Then escalate critical
- Name: low space in root partition
  Description: Escalates to Critical Alert if space drops below 1G
  Clause: If df-root/df_complex-free.value < 1000000000 for 5 minutes Then escalate
    critical
- Name: low space in mnt storage partition
  Description: Critically Alerts if /mnt/storage drops below 1G
  Clause: If df-mnt-storage/df_complex-free.value < 1000000000 for 5 minutes Then
    escalate critical
- Name: mysqld process dead
  Description: Alerts if mysql process goes to 0
  Clause: If processes-mysqld/ps_count.processes < 1 for 1 minutes Then escalate critical
- Name: MySQL Slave 30 Seconds Behind Master
  Description: Will alert if slave is 30 seconds behind master for 5 minutes
  Clause: If mysql_seconds_behind_master/gauge-seconds.value > 30 for 5 minutes Then
    escalate warning
- Name: MySQL Slave 60 Seconds Behind Master
  Description: Will alert critical if slave falls 60 seconds behind master
  Clause: If mysql_seconds_behind_master/gauge-seconds.value >= 60 for 5 minutes Then
    escalate critical
- Name: MySQL Slave Threads are down
  Description: Will alert if mysql slave threads are down
  Clause: If mysql_slave_running/gauge-operations.value != 2 for 2 minutes Then escalate
    critical
